# Generated by Django 5.2.1 on 2025-05-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('Name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Actor', models.CharField(max_length=25)),
                ('Language', models.CharField(max_length=20)),
                ('Budget', models.IntegerField()),
                ('Genre', models.CharField(max_length=20)),
                ('ReleaseDate', models.DateField()),
            ],
        ),
    ]
